import { itemDefinitions } from "./helpers";

// Curated seed lists. TempleOSRS category data extends these rows dynamically for synced players.
export const clueItems = [
  ...itemDefinitions("clues-beginner-treasure-trails", [
    "Mole slippers",
    "Frog slippers",
    "Bear feet",
    "Demon feet",
    "Jester cape",
    "Shoulder parrot",
    "Monk's robe top (t)",
    "Monk's robe (t)",
    "Sandwich lady hat",
    "Sandwich lady top",
    "Sandwich lady bottom",
    "Rune scimitar ornament kit (guthix)"
  ]),
  ...itemDefinitions("clues-easy-treasure-trails", [
    "Black full helm (g)",
    "Black platebody (g)",
    "Black platelegs (g)",
    "Black kiteshield (g)",
    "Black full helm (t)",
    "Black platebody (t)",
    "Black platelegs (t)",
    "Black kiteshield (t)",
    "Blue wizard hat (g)",
    "Blue wizard robe (g)",
    "Blue skirt (g)",
    "Blue wizard hat (t)",
    "Blue wizard robe (t)",
    "Blue skirt (t)",
    "Studded body (g)",
    "Studded chaps (g)",
    "Studded body (t)",
    "Studded chaps (t)",
    "Amulet of magic (t)",
    "Cape of skulls",
    "Flared trousers",
    "Ham joint",
    "Golden chef's hat",
    "Golden apron"
  ]),
  ...itemDefinitions("clues-medium-treasure-trails", [
    "Ranger boots",
    "Wizard boots",
    "Holy sandals",
    "Spiked manacles",
    "Climbing boots (g)",
    "Adamant full helm (g)",
    "Adamant platebody (g)",
    "Adamant platelegs (g)",
    "Adamant kiteshield (g)",
    "Adamant full helm (t)",
    "Adamant platebody (t)",
    "Adamant platelegs (t)",
    "Adamant kiteshield (t)",
    "Mithril full helm (g)",
    "Mithril platebody (g)",
    "Mithril platelegs (g)",
    "Mithril kiteshield (g)"
  ]),
  ...itemDefinitions("clues-hard-treasure-trails", [
    "Robin hood hat",
    "Rangers' tunic",
    "Amulet of glory (t)",
    "Rune full helm (g)",
    "Rune platebody (g)",
    "Rune platelegs (g)",
    "Rune kiteshield (g)",
    "Rune full helm (t)",
    "Rune platebody (t)",
    "Rune platelegs (t)",
    "Rune kiteshield (t)",
    "Gilded full helm",
    "Gilded platebody",
    "Gilded platelegs",
    "Gilded kiteshield",
    "Magic shortbow scroll"
  ]),
  ...itemDefinitions("clues-elite-treasure-trails", [
    "Rangers' tights",
    "Fury ornament kit",
    "Musketeer hat",
    "Musketeer tabard",
    "Musketeer pants",
    "Dragon cane",
    "Top hat",
    "Briefcase",
    "Sagacious spectacles",
    "Royal crown",
    "Royal gown top",
    "Royal gown bottom"
  ]),
  ...itemDefinitions("clues-master-treasure-trails", [
    "Bloodhound",
    "3rd age pickaxe",
    "3rd age axe",
    "3rd age druidic robe top",
    "3rd age druidic robe bottoms",
    "3rd age druidic staff",
    "3rd age druidic cloak",
    "Ring of coins",
    "Ale of the gods",
    "Bucket helm",
    "Flaming sword enchantment",
    "Occult ornament kit"
  ])
];
